#!/bin/bash

set -e

# Modules
for ext in \
  reitit-core \
  reitit-spec \
  reitit-schema \
  reitit-ring \
  reitit-middleware \
  reitit-http \
  reitit-interceptors \
  reitit-swagger \
  reitit-swagger-ui \
  reitit-frontend \
  reitit-sieppari \
  reitit; do
  cd modules/$ext; lein "$@"; cd ../..;
done
